version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: vendor_portal_postgres
    environment:
      POSTGRES_DB: vendor_portal
      POSTGRES_USER: vendor_app
      POSTGRES_PASSWORD: vendor_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vendor_app"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
